### ISSUE TITLE
Strange characters in the excel file (Spanish language)

### ISSUE THREAD

**Issue by sebosovil** [KagariSoft/renxel#9]
Letters such as "ñ  á  é  í  ó  ú  Á  É  Í  Ó Ú", and signs such as "¿ ¡" appear strangely in the excel file, making it very annoying to read.

Examples:

![image](https://user-images.githubusercontent.com/53313950/211442775-0935ae94-7fbd-4123-9731-f5716f96be58.png)
![image](https://user-images.githubusercontent.com/53313950/211443275-86d35b52-a1d5-4641-91ca-11651d056a19.png)
![image](https://user-images.githubusercontent.com/53313950/211443312-8aa98c3e-8c53-4bc5-b81a-b46e31804dbe.png)

**Comment by Neyunse** [comment]
> Letters such as "ñ á é í ó ú Á É Í Ó Ú", and signs such as "¿ ¡" appear strangely in the excel file, making it very annoying to read.
> 
> Examples:
> 
> ![image](https://user-images.githubusercontent.com/53313950/211442775-0935ae94-7fbd-4123-9731-f5716f96be58.png) ![image](https://user-images.githubusercontent.com/53313950/211443275-86d35b52-a1d5-4641-91ca-11651d056a19.png) ![image](https://user-images.githubusercontent.com/53313950/211443312-8aa98c3e-8c53-4bc5-b81a-b46e31804dbe.png)

Spanish is the default lang?

**Comment by sebosovil** [comment]
Yes, it is, I also checked the game files in vscode to see if the problem was the encoding but they are in utf-8, so I don't know what the problem might be.

**Comment by Neyunse** [comment]
@sebosovil try the new version

**Comment by sebosovil** [comment]
> @sebosovil try the new version

Works perfectly, thank you!
